export const PROVINCES = [
  { official: "CORUÑA (A)", name: "A Coruña", slug: "a-coruna" },
  { official: "ARABA/ÁLAVA", name: "Álava", slug: "alava" },
  { official: "ALBACETE", name: "Albacete", slug: "albacete" },
  { official: "ALICANTE", name: "Alicante", slug: "alicante" },
  { official: "ALMERÍA", name: "Almería", slug: "almeria" },
  { official: "ASTURIAS", name: "Asturias", slug: "asturias" },
  { official: "ÁVILA", name: "Ávila", slug: "avila" },
  { official: "BADAJOZ", name: "Badajoz", slug: "badajoz" },
  { official: "BALEARS (ILLES)", name: "Illes Balears", slug: "illes-balears" },
  { official: "BARCELONA", name: "Barcelona", slug: "barcelona" },
  { official: "BIZKAIA", name: "Bizkaia", slug: "bizkaia" },
  { official: "BURGOS", name: "Burgos", slug: "burgos" },
  { official: "CÁCERES", name: "Cáceres", slug: "caceres" },
  { official: "CÁDIZ", name: "Cádiz", slug: "cadiz" },
  { official: "CANTABRIA", name: "Cantabria", slug: "cantabria" },
  { official: "CASTELLÓN / CASTELLÓ", name: "Castellón", slug: "castellon" },
  { official: "CEUTA", name: "Ceuta", slug: "ceuta" },
  { official: "CIUDAD REAL", name: "Ciudad Real", slug: "ciudad-real" },
  { official: "CÓRDOBA", name: "Córdoba", slug: "cordoba" },
  { official: "CUENCA", name: "Cuenca", slug: "cuenca" },
  { official: "GIPUZKOA", name: "Gipuzkoa", slug: "gipuzkoa" },
  { official: "GIRONA", name: "Girona", slug: "girona" },
  { official: "GRANADA", name: "Granada", slug: "granada" },
  { official: "GUADALAJARA", name: "Guadalajara", slug: "guadalajara" },
  { official: "HUELVA", name: "Huelva", slug: "huelva" },
  { official: "HUESCA", name: "Huesca", slug: "huesca" },
  { official: "JAÉN", name: "Jaén", slug: "jaen" },
  { official: "LEÓN", name: "León", slug: "leon" },
  { official: "LLEIDA", name: "Lleida", slug: "lleida" },
  { official: "LUGO", name: "Lugo", slug: "lugo" },
  { official: "MADRID", name: "Madrid", slug: "madrid" },
  { official: "MÁLAGA", name: "Málaga", slug: "malaga" },
  { official: "MELILLA", name: "Melilla", slug: "melilla" },
  { official: "MURCIA", name: "Murcia", slug: "murcia" },
  { official: "NAVARRA", name: "Navarra", slug: "navarra" },
  { official: "OURENSE", name: "Ourense", slug: "ourense" },
  { official: "PALENCIA", name: "Palencia", slug: "palencia" },
  { official: "PALMAS (LAS)", name: "Las Palmas", slug: "las-palmas" },
  { official: "PONTEVEDRA", name: "Pontevedra", slug: "pontevedra" },
  { official: "RIOJA (LA)", name: "La Rioja", slug: "la-rioja" },
  { official: "SALAMANCA", name: "Salamanca", slug: "salamanca" },
  { official: "SANTA CRUZ DE TENERIFE", name: "Santa Cruz de Tenerife", slug: "santa-cruz-de-tenerife" },
  { official: "SEGOVIA", name: "Segovia", slug: "segovia" },
  { official: "SEVILLA", name: "Sevilla", slug: "sevilla" },
  { official: "SORIA", name: "Soria", slug: "soria" },
  { official: "TARRAGONA", name: "Tarragona", slug: "tarragona" },
  { official: "TERUEL", name: "Teruel", slug: "teruel" },
  { official: "TOLEDO", name: "Toledo", slug: "toledo" },
  { official: "VALENCIA / VALÈNCIA", name: "Valencia", slug: "valencia" },
  { official: "VALLADOLID", name: "Valladolid", slug: "valladolid" },
  { official: "ZAMORA", name: "Zamora", slug: "zamora" },
  { official: "ZARAGOZA", name: "Zaragoza", slug: "zaragoza" },
] as const;

export function displayProvince(value: string | null) {
  return PROVINCES.find((province) => province.official === value)?.name || value || "";
}

export function provinceBySlug(slug: string) {
  return PROVINCES.find((province) => province.slug === slug);
}
